config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  namespace :admin, path: 'implicit' do
    get 'sessions/new'
    resources :users do
      resources :tasks
    end
  end

  get 'sessions/new'
  get 'tasks/home' => 'tasks#home', as: 'home_task'
  root 'tasks#index'
  resources :tasks
  resources :users

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  #relation
  belongs_to :user
  has_many :label_maps
  has_many :labels, through: :label_maps

  #validates
  validates :user_id, :start_time, :end_time, :task_name, presence: true
  validates :priority, presence: true, numericality: {
    greater_than_or_equal_to: 0, less_than_or_equal_to: 5
  }
  validates :status, presence: true, numericality: {
    greater_than_or_equal_to: 0, less_than_or_equal_to: 2
  }
  validate :validate_content_with_task_name

  #class method
  def self.by_status(status)
    status.blank? ? all : where(status: status)
  end

  def self.by_priority(priority)
    priority.blank? ? all : where(priority: priority)
  end

  def self.by_keyword(keyword)
    keyword.blank? ? all : where("task_name ILIKE :search OR content ILIKE :search", search: "%#{keyword}%")
  end

  def self.by_user_id(user_id)
    user_id.blank? ? all : where(user_id: user_id)
  end

  def self.filtered(query_params)
    labeled_with(query_params[:label_keyword]).by_user_id(query_params[:user_id]).by_status(query_params[:status]).by_priority(query_params[:priority]).by_keyword(query_params[:keyword])
  end

  #method
  def validate_content_with_task_name
    if ( task_name.present? && content.blank? )
      errors.add(:content, I18n.t('errors.task_name_without_content'))
    end
    if ( task_name.blank? && content.present? )
      errors.add(:task_name, I18n.t('errors.content_without_task_name'))
    end
  end

  def self.labeled_with(label_keyword)
    label_keyword.blank? ? all : joins(:labels).where("labels.label_name = ?", label_keyword)
  end

  def label_list
    labels.map(&:label_name).join(', ')
  end

  def label_list=(names)
    self.labels = names.split(',').map do |item|
      Label.where(label_name: item.strip).first_or_create!
    end
  end
end

app/controllers/admin/tasks_controller.rb
class Admin::TasksController < Admin::BaseController
  before_action :task_find_by_id, only:[:edit, :update, :destroy]
  before_action :instance_var,    only: [:index]
  
  def index
    @tasks = Task.where(user_id: params[:user_id]).page(params[:page]).per(5)
  end

  def instance_var
    @status_list = ["Pending", "In Progress", "Complete"]
    @priority_list = ["Urgent", "Highest", "High", "Normal", "Low", "Lowest"]
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :task_find_by_id, only:[:edit, :update, :destroy]
  before_action :status_priority_list,    only: [:index, :edit]

  def index
    @tasks = current_scope.filtered(query_params).page(params[:page]).per(5).order(sort_column + " " + sort_direction)
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      flash.now[:success] = I18n.t('task_relate.add_success')
      redirect_to root_path
    else
      flash.now[:error] = I18n.t('task_relate.add_fails')
      render :new
    end
  end

  def edit
  end

  def show
    @tasks = Task.where("tasks.user_id = " + params['id']).page(params[:page]).per(5)
  end

  def update
    if @task.update(task_params)
      flash[:success] = I18n.t('task_relate.edit_success')
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @task.destroy if @task
      flash[:success] = I18n.t('task_relate.delete_success')
      redirect_to root_path
  end

  private

  def current_scope
    current_user ? current_user.tasks : Task
  end

  def task_params
    params.require(:task).permit(:user_id, :task_name, :content, :start_time, :end_time, :priority, :status, :label_list)
  end

  def query_params
    query_params = params[:query]
    query_params ? query_params.permit(:keyword, :status, :priority, :user_id, :label_keyword) : {}
  end

  def task_find_by_id
    @task = current_scope.find(params['id'])
  end

  def status_priority_list
    @status_list = ["Pending", "In Progress", "Complete"]
    @priority_list = ["Urgent", "Highest", "High", "Normal", "Low", "Lowest"]
  end

end
  

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for task, url: locals[:url], method: locals[:method] do |t| %>
  <% if current_user %>
    <% if action_name.include?("new") %>
      <% locals_action = "add_task" %>
    <% elsif action_name.include?("edit") %>
      <% locals_action = "edit_task" %>
    <% end %>
    User ID:<%= current_user.id %>
    User Name: <%= current_user.username %>
    <%= locals[:url] %>
    <%= t.hidden_field :user_id, value: current_user.id %>
  <% end %>
  
  <div class="form-group">
    <%= t.label :task_name, Task.human_attribute_name("tasks.task_name") %>
    <%= t.text_field :task_name, class: "form-control" %>
  </div>
  <div class="form-group" style="height:300px">
    <%= t.label :content, Task.human_attribute_name("tasks.content") %>
    <%= t.text_area :content, class: "form-control h-75" %>
  </div>
  <div class="form-group">
    <%= t.label :start_time, Task.human_attribute_name("tasks.start_time") %>
    <%= t.datetime_select :start_time, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= t.label :end_time, Task.human_attribute_name("tasks.end_time") %>
    <%= t.datetime_select :end_time, class: "form-control" %>
  </div>
  <div class="form-group" style="display:inline-block;">
    <%= t.label :priority, Task.human_attribute_name("tasks.priority") %>
    <%= t.number_field :priority, in: 0...6, class: "form-control" %>
  </div>
  <div class="form-group" style="display:inline-block;">
    <%= t.label :status, Task.human_attribute_name("tasks.status") %>
    <%= t.number_field :status, in: 0...3, class: "form-control" %>
  </div>
  <div class="form-group" >
    <%= t.label :label_list, t("task_relate.task_label") %>
    <%= t.text_field :label_list, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= t.submit t( "task_relate." + locals_action.to_s ), class: "btn btn-primary form-control" %>
  </div>
<% end %>

<% if @task.errors.any? %>
  <ul style="color:red">
    <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/tasks/_header.html.erb
<% if logged_in? && current_user.admin? %>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
<% else %>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
<% end %>
  <%= link_to t('home_page'), home_task_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to t('task_relate.add_task'), new_task_path, class:"nav-link" %>
        </li>
        
        <% if logged_in? && current_user.admin? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= t('admin_page') %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to t('user_relate.user_list'), admin_users_path, class:"dropdown-item" %>
            </div>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= t('user_relate.user_account') %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <!--%= link_to t('user_relate.user_task'), show_user_path(session[:user_id]), class:"dropdown-item" %-->
            <%= link_to t('user_relate.user_task'), root_path(session[:user_id]), class:"dropdown-item" %>
            <% if current_user.admin? %>
              <%= link_to t('user_relate.user_setting'), edit_admin_user_path(current_user), class:"dropdown-item" %>
            <% else %>
              <%= link_to t('user_relate.user_setting'), edit_user_path(current_user), class:"dropdown-item" %>
            <% end %>
            <div class="dropdown-divider"></div>
            <%= link_to t('user_relate.logout_user'), logout_path, method: "delete", class:"dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to t('user_relate.add_user'), new_user_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to t('user_relate.login_user'), login_path, class:"nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/tasks/about.html.erb
<h1>About Us ...</h1>

app/views/tasks/edit.html.erb
<div class="container">
  <br/>
  <h1><%= t('task_relate.edit_task') %></h1>

  <div style="color:red">
    <%= flash[:error]%>
  </div>
  <%= render "form", task: @task, locals: { url: task_path(@task), method: :patch } %>
  <br />
  <%= link_to t('task_relate.back_to_task_list'), root_path %>
</div>

app/views/tasks/home.html.erb
<% if logged_in? && current_user.admin? %>
  <div class="masthead " style="background-image: url('/home_admin.PNG'); height:500px; width:100%; background-size: 100% 120%;">
<% else %>
  <div class="masthead " style="background-image: url('/home_img.png'); height:500px; width:100%; background-size: 100% 120%;">
<% end %>
  <div class="container position-relative" style="top:10%; ">
    <div class="row gx-4 gx-lg-5 justify-content-left">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1 class="text-white display-3">Task Management</h1>
        </div>
      </div>
    </div>
  </div>
</div>

<section id="first">
  <div class="container px-4">
    <div class="row gx-4 justify-content-center">
      <div class="col-lg-8" >
        <br/><br/><br/><br/><br/><br/>
        <h1>First</h1>
        <p class="lead">Try to Sign Up and Log in!</p>
        <br/><br/><br/><br/><br/><br/>
      </div>
    </div>
  </div>
</section>

<section id="second" class="bg-light">
  <div class="container px-4">
    <div class="row gx-4 justify-content-center">
      <div class="col-lg-8" >
        <br/><br/><br/><br/><br/><br/>
        <h1>Second</h1>
        <p class="lead">Try to Add/Edit/Delete the Task!</p>
        <br/><br/><br/><br/><br/><br/>
      </div>
    </div>
  </div>
</section>

<!--section id="about">
  <div class="container px-4">
    <div class="row gx-4 justify-content-center">
      <div class="col-lg-8" >
        <br/><br/><br/>
        <h2>About This Page</h2>
        <p class="lead">Here provide the several functions:</p>
        <ul>
          <li>List the task order by the table attribute.</li>
          <li>Search by keyword, priority, and status simultaneously.</li>
          <li>Use the session to log in and log out.</li>
        </ul>
      </div>
    </div>
  </div>
</section-->

app/views/tasks/index.html.erb
<div class="container">
  <% if logged_in? %>
    <div class="container-fluid">
      <br/>
      <h1><%= @current_user.username %> <%= t('task_relate.task_list') %></h1>
      <p><%= user_role(@current_user.admin) %></p>

      <div style="margin-left: auto; margin-right: 0;">
        <%= form_for :query, url: root_path, method: :get do |form| %>
          <%= form.hidden_field :user_id, value: current_user.id %>
          <div class="field form-group" style="display:inline-block;">
            <%= form.text_field :keyword, placeholder: t('task_relate.enter_keyword'), value: params.dig('query', 'keyword'), class: "form-control" %>
          </div>
          <div class="field form-group" style="display:inline-block;">
            <%= form.text_field :label_keyword, placeholder: t('task_relate.enter_label_keyword'), value: params.dig('query', 'label_keyword'), class: "form-control" %>
          </div>
          <div class="field form-group" style="display:inline-block;">
            <%= form.select :priority, options_for_select([[Task.human_attribute_name("tasks.priority"), nil], ['Urgent', 0], ['Highest', 1], ['High', 2], ['Normal', 3], ['Low', 4], ['Lowest', 5]]), {}, class: "form-control", selected: params.dig('query', 'status'), id: "task_priority" %>
          </div>
          <div class="field form-group" style="display:inline-block;">
            <%= form.select :status, options_for_select([[Task.human_attribute_name("tasks.status"), nil], ['Pending', 0], ['In progress', 1], ['Complete', 2]]), {}, class: "form-control", selected: params.dig('query', 'status'), id: "task_status" %>
          </div>
          <div class="actions form-group" style="display:inline-block;">
            <%= form.submit t('task_relate.serch_task'), class: "form-control" %>
          </div>
        <% end %>
      </div>
      <div style="color:red">
          <%= flash[:error]%>
      </div>
      <div style="color:green">
          <%= flash[:success]%>
      </div>

      <%= link_to t('task_relate.add_task'), new_task_path %>

      <div class="dropdown clearfix pull-right">
      <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      <%= t('sort.sort_title') %>
          <span class="caret"></span>
      </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider">
          <li>
            <%= link_to( t('sort.sort_create_time_desc'), root_path(:order => "created_at desc", :user_id => session[:user_id])) %>
          </li>
          <li>
            <%= link_to( t('sort.sort_create_time_asc'), root_path(:order => "created_at asc", :user_id => session[:user_id])) %>
          </li>
          <li>
            <%= link_to( t('sort.sort_priority_desc'), root_path(:order => "priority desc", :user_id => session[:user_id])) %>
          </li>
          <li>
            <%= link_to( t('sort.sort_priority_asc'), root_path(:order => "priority asc", :user_id => session[:user_id])) %>
          </li>
          <li>
            <%= link_to( t('sort.sort_status_desc'), root_path(:order => "status desc", :user_id => session[:user_id])) %>
          </li>
          <li>
            <%= link_to( t('sort.sort_status_asc'), root_path(:order => "status asc", :user_id => session[:user_id])) %>
          </li>
          
          <li>
            <%= link_to( t('sort.sort_start_time_desc'), root_path(:order => "start_time desc", :user_id => session[:user_id])) %>
          </li>
          <li>
            <%= link_to( t('sort.sort_start_time_asc'), root_path(:order => "start_time asc", :user_id => session[:user_id])) %>
          </li>

          <li>
            <%= link_to( t('sort.sort_end_time_desc'), root_path(:order => "end_time desc", :user_id => session[:user_id])) %>
          </li>
          <li>
            <%= link_to( t('sort.sort_end_time_asc'), root_path(:order => "end_time asc", :user_id => session[:user_id])) %>
          </li>

          <li>
            <%= link_to(t('sort.sort_id_desc'), root_path(:order => "id desc", :user_id => session[:user_id]) ) %>
          </li>
          <li>
            <%= link_to(t('sort.sort_id_asc'), root_path(:order => "id asc", :user_id => session[:user_id]) ) %>
          </li>
        </ul>
      </div>
      <div class="table-responsive">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th> <%= Task.human_attribute_name("tasks.user_id") %> </th>
              <th> <%= Task.human_attribute_name("tasks.task_name") %> </th>
              <th> <%= Task.human_attribute_name("tasks.content") %> </th>
              <th> <%= Task.human_attribute_name("tasks.start_time") %> </th>
              <th> <%= Task.human_attribute_name("tasks.end_time") %> </th>
              <th> <%= Task.human_attribute_name("tasks.priority") %> </th>
              <th> <%= Task.human_attribute_name("tasks.status") %> </th>
              <th> <%= Task.human_attribute_name("tasks.create_time") %> </th>
              <th> <%= t("task_relate.task_label") %> </th>
              <th> <%= Task.human_attribute_name("tasks.handle") %> </th>
            </tr>
          </thead>
          <tbody>
            <% @tasks.each do |task| %>
            <tr>
              <td><%= task.user_id %></td>
              <td><%= task.task_name %></td>
              <td><%= task.content %></td>
              <td><%= task.start_time %></td>
              <td><%= task.end_time %></td>
              <td><%= @priority_list[task.priority] %></td>
              <td><%= @status_list[task.status] %></td>
              <td><%= task.created_at %></td>
              <td><%= task.label_list %>
              <td>
                <%= link_to t('task_relate.edit_task'), edit_task_path(task) %>
                <%= link_to t('task_relate.delete_task'), task_path(task), method: :delete, data: { confirm: "Comfirm to delete it" } %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div sytle="margin: auto;">
          <%= paginate @tasks %>
        </div>
      </div>
    </div>
  <% else %>
    <h1>Please Log In First.</h1>
  <% end %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <br/>
  <h1><%= t('task_relate.add_task') %></h1>

  <div style="color:red">
    <%= flash[:error]%>
  </div>

  <%= render "form", task: @task, locals: { url: tasks_path("create"), method: :post } %>

  <br />
  <%= link_to t('task_relate.back_to_task_list'), root_path %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <% provide(:title, 'tasks') %>
  <br />
  <h1><%= User.find(params[:id]).username %> <%= t('task_relate.task_list') %></h1>
  <%
    $status_list = ["Pending", "In Progress", "Complete"]
    $priority_list = ["Urgent", "Highest", "High", "Normal", "Low", "Lowest"]
  %>
  <div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
          <th> <%= Task.human_attribute_name("tasks.user_id") %> </th>
          <th> <%= Task.human_attribute_name("tasks.task_name") %> </th>
          <th> <%= Task.human_attribute_name("tasks.content") %> </th>
          <th> <%= Task.human_attribute_name("tasks.start_time") %> </th>
          <th> <%= Task.human_attribute_name("tasks.end_time") %> </th>
          <th> <%= Task.human_attribute_name("tasks.priority") %> </th>
          <th> <%= Task.human_attribute_name("tasks.status") %> </th>
          <th> <%= Task.human_attribute_name("task_relate.task_label") %> </th>
          <th> <%= Task.human_attribute_name("tasks.create_time") %> </th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
            <td><%= task.user_id %></td>
            <td><%= task.task_name %></td>
            <td><%= task.content %></td>
            <td><%= task.start_time %></td>
            <td><%= task.end_time %></td>
            <td><%= $priority_list[task.priority] %></td>
            <td><%= $status_list[task.status] %></td>
            <td><%= task.label_list %></td>
            <td><%= task.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div sytle="margin: auto;">
      <%= paginate @tasks %>
  </div>
</div>