config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  namespace :admin, path: 'implicit' do
    get 'sessions/new'
    resources :users do
      resources :tasks
    end
  end

  get 'sessions/new'
  get 'tasks/home' => 'tasks#home', as: 'home_task'
  root 'tasks#index'
  resources :tasks
  resources :users

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  #attr_accessor :username, :email
  attr_accessor :current_password

  #relation
  has_many :tasks, dependent: :destroy
  #validates
  validates :username, :presence => { :message => I18n.t('errors.username_blank') },
                       :uniqueness => { :message => I18n.t('errors.username_uniqueness')}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :presence => { :message => I18n.t('errors.email_blank') },
                    :uniqueness => { :message => I18n.t('errors.email_uniqueness')},
                    :format => { with: VALID_EMAIL_REGEX }

  has_secure_password
  validates_presence_of :password, :if => :password_required?
  validate :password_requirements, :if => :password_required?
  validates :password, confirmation: { case_sensitive: true }, :if => :password_required?

  #validates_presence_of :current_password, on: :update #if use validates instead of the if condition in the :same_password_is_correct method will couldn't get the current_password (get nil)
  validate :same_password_is_correct, on: :update
  
  #callback
  before_save { username.downcase! }
  before_save { email.downcase! }

  #constant
  Rules = { #constant: start with capital letters
    I18n.t('errors.password_no_lowercase')  => /[a-z]+/,
    I18n.t('errors.password_no_uppercase')  => /[A-Z]+/,
    I18n.t('errors.password_no_digit')      => /\d+/
  }

  #method
  def password_requirements
    Rules.each do |message, regex|
      errors.add( :password, message ) unless password.to_s().match( regex )
    end
  end

  def same_password_is_correct
    unless current_password.blank?
      unless current_user.admin && current_user.authenticate(current_password)
        errors.add(:current_password, I18n.t('errors.password_diff'))
      end
    end
  end

  def password_required?
    not password.blank?
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :user_find_by_id, only:[:edit, :update, :destroy]
  before_action :correct_user,    only: [:edit, :update]
  before_action :is_last_admin,   only: [:destroy]

  def index
    @users = User.page(params[:page]).per(3)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = I18n.t('user_relate.add_success')
      if current_user.admin
        redirect_to admin_users_path
      end
    else
      flash[:error] = I18n.t('user_relate.add_fails')
      render :action => :new
    end
  end

  def edit
    current_user = current_user
  end

  def update
    if @user.update(user_params)
      flash[:success] = I18n.t('user_relate.edit_success')
      redirect_to :edit_admin_user, :id => @user
    else
      render :edit
    end
  end

  def destroy
    delete_user = User.find(params[:id])
    delete_user.destroy
    flash[:success] = I18n.t('user_relate.delete_success')
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :admin)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path if @user != current_user && !current_user.admin?
  end

  def user_find_by_id
    @user = User.find(params['id'])
  end

  def is_last_admin
    @admins = User.where(:admin => true)
    if @admins.size == 1
      flash[:error] = I18n.t('user_relate.at_least_one_admin')
      redirect_to admin_users_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_find_by_id, only:[:edit, :update, :destroy]
  before_action :logged_in_user,  only: [:index, :edit, :update, :destroy]
  before_action :correct_user,    only: [:edit, :update]

  def index
    flash[:error] = "Permission denied"
    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = I18n.t('user_relate.add_success')
      redirect_to login_path
    else
      flash[:error] = I18n.t('user_relate.add_fails')
      render :action => :new
    end
  end

  def edit
    current_user = current_user
  end

  def update
    if @user.update(user_params)
      flash[:success] = I18n.t('user_relate.edit_success')
      redirect_to :edit_user, :id => @user
    else
      render :edit
    end
    #debugger
  end

  private
  def authorize_admin
    redirect_to root_path, alert: "Permissions denied" unless
      current_user.admin?
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      flash[:error] = "Please log in."
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) if @user != current_user && !current_user.admin?
  end

  def user_find_by_id
    @user = User.find(params['id'])
  end

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def user_role(x)
    key = x ? 'admin' : 'member'
    I18n.t('role_' + key, scope: :user_relate)
  end
end

app/views/users/_form.html.erb
<%= form_for user, url: locals[:url], method: locals[:method] do |f| %>
  <div class="form-group">
    <%= f.label :usesrname, User.human_attribute_name("users.username") %>
    <%= f.text_field :username, class: "form-control" %>
  </div>
  <% if action_name.include?("new") %>
    <% locals_action = "add_user" %>
  <% elsif action_name.include?("edit") %>
    <% locals_action = "edit_user" %>
  <% end %>

  <div class="form-group">
    <%= f.label :email, User.human_attribute_name("users.email") %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <% if locals[:url].include?("edit") %>
    <% if user.id == current_user.id %>
      <div class="form-group">
        <%= f.label :password, t('user_relate.new_password') %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, t('user_relate.new_password_comfirmation') %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :current_password, t('user_relate.current_password') %>
        <%= f.password_field :current_password, class: "form-control" %>
      </div>
    <% elsif current_user.admin %>
      <div class="form-group">
        <%= f.label :current_password, t('user_relate.role_admin_password') %>
        <%= f.password_field :current_password, class: "form-control" %>
      </div>
    <% end %>
  <% else %>
    <div class="form-group">
      <%= f.label :password, User.human_attribute_name("users.password") %>
      <%= f.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, t('user_relate.password_comfirmation') %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  <% end %>

  <div class="form-group">
  <%= f.submit t( "user_relate." + locals_action.to_s ), class: "btn btn-primary form-control" %>
  </div>
<% end %>

<% if @user.errors.any? %>
  <ul style="color:red">
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <br/>
  <% provide(:title, 'Edit Account') %>
  <div style="color:green">
    <%= flash[:success]%>
  </div>

  <div style="color:red">
    <%= flash[:error]%>
  </div>
  <div>
    <h1><%= t('user_relate.edit_user') %></h1>
      <br />
      <div class="row", style="margin: auto;">
        <div class="col-md-6 col-md-offset-3">
          <%= render "form", user: @user, locals: { url: user_path(@user), method: :patch } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <% provide(:title, 'All users') %>
  <br />
  <h1><%= t('user_relate.user_list') %></h1>
  <%= link_to t('user_relate.add_user'), new_user_path %>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
        <th> <%= User.human_attribute_name("users.id") %> </th>
          <th> <%= User.human_attribute_name("users.username") %> </th>
          <th> <%= User.human_attribute_name("users.email") %> </th>
          <th> <%= User.human_attribute_name("users.create_time") %> </th>
          <th> <%= t("user_relate.num_of_tasks") %> </th>
          <% if current_user.admin? && !current_user?(@user) %>
            <th> <%= User.human_attribute_name("users.handle") %> </th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.username %></td>
          <td><%= user.email %></td>
          <td><%= user.created_at %></td>
          <td><%= user.tasks.count %></td>
          <% if current_user.admin? && !current_user?(user) %>
            <td>
              <%= link_to t('task_relate.task_list'), show_task_path(user) %>
              <%= link_to t('user_relate.edit_user'), edit_user_path(user) %>
              <%= link_to t('user_relate.delete_user'), edit_user_path(user), method: "delete", data: { confirm: "Comfirm to delete acoount: " + user.username } %>
            </td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div sytle="margin: auto;">
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <br/>
  <% provide(:title, 'Sign up') %>

  <div style="color:green">
  <%= flash[:success]%>
  </div>

  <div style="color:red">
      <%= flash[:error]%>
  </div>

  <div>
    <h1><%= t('user_relate.add_user') %></h1>
    <br />
    <div class="row", style="margin: auto;">
    <div class="col-md-6 col-md-offset-3">
        <%= render "form", user: @user, locals: { url: users_path(@user), method: :post } %>
    </div>
    </div>
  </div>
</div>